#!/bin/bash

# Source hannah dee (http://www.hannahdee.eu/blog/?p=835)

# Download
url=$1
sudo wget -P /usr/share/texmf/tex/latex/ "$url"

# Unzip
zipfile="/usr/share/texmf/tex/latex/$(basename $url)"
exdir="$(echo $zipfile | cut -d. -f1)"  
sudo unzip $zipfile -d $exdir

# Does .ins exist?
insfile="$(find $exdir -name '*.ins')"
if test -z "$insfile"
then
	echo "\$insfile does not exist!"
else
	echo "installing latex package..."
	sudo latex -output-directory $exdir $insfile
fi

# Update latex
sudo texhash

# Clean up
sudo rm $zipfile
