#!/bin/bash

# Beep - The traditional method of producing a beep in a shell script is to 
# write an ASCII BEL (\007) character to standard output, by means of a shell
# command such as:

echo -ne '\007'

# From echox on stackoverflow:
# https://unix.stackexchange.com/questions/1974/how-do-i-make-my-pc-speaker-beep
