#!/bin/bash

# Open Google Chrome web browser.
#cd "/mnt/c/Program Files (x86)/Google/Chrome/Application/"
#./chrome.exe $1

"/mnt/c/Program Files (x86)/Google/Chrome/Application/chrome.exe" "$1"

C:\ProgramData\Microsoft\Windows\Start Menu\Programs

# To search google, use the following format:
# chrome "? <your search term>"
