#!/bin/bash

## Configuring the home directory on WSL.
# USAGE:
# $ ~/bin/config-home

# System update.
sudo apt-get -y update

# Pull dotfiles and configure.
git clone https://github.com/twesleyb/dotfiles.git
~/dotfiles/config

# Configure Vim: get Vundle and install plugins.
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Configure Tmux: get TPM and install plugins.
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Link key Windows directories.
ln -s "/mnt/c/Users/khoss/Downloads/" ~/downloads
ln -s "/mnt/c/Users/khoss/Documents/Projects(LAB)/" ~/projects
ln -s "/mnt/c/Users/khoss/Documents/Projects(LAB)/bin/" ~/bin

# Reload bashrc.
source ~/.bashrc
