#!/bin/bash

# Usage:
# $ config-r [<path/to/local/R/library/>]

# Where should local R packages be installed?

# If no directory is passed as input to the function, then default to ~/local/R_libs
if [ $# -eq 0 ]
then
	lib_path="$(echo ~/local)/R_libs"
	echo "R packages will be installed in $lib_path"
	[ ! -d "$lib_path" ] && mkdir -p "$lib_path"
fi

# Create .Renviron file if it does not exist.
if [ ! -f ~/.Renviron ]
then
	touch ~/.Renviron
	echo "R_LIBS=$lib_path" > ~/.Renviron
fi

# Create .Rprofile file if it does not exist.
if [ ! -f ~/.Rprofile ]
then 
	touch ~/.Rprofile
	echo "Created .Rprofile!"
fi

# Insure that user is added to libPaths!
user=$(whoami)
sudo chgrp $user /usr/lib/R/site-library/
sudo chgrp $user /usr/local/lib/R/site-library/
sudo chgrp $user /usr/lib/R/library/

# Make sure that user has write access.
sudo chmod g+w /usr/lib/R/site-library/
sudo chmod g+w /usr/local/lib/R/site-library/
sudo chmod g+w /usr/lib/R/library/


