#!/bin/bash
# Usage:
# $ config-r [<path/to/local/R/library/>]

# Where should local R packages be installed?

# If no directory is passed as input to the function, then default to ~/R_lib
if [ $# -eq 0 ]
then
	lib_path="R_libs"
	home_dir="$(echo ~/)"
	echo "R packages will be installed in "$home_dir$lib_path""
	[ ! -d "$home_dir$lib_path" ] && mkdir "$home_dir$lib_path"
fi

# Update .Renviron configuration file.
[ ! -f "~/.Renviron" ] && touch ~/.Renviron
echo "R_LIBS=$home_dir$lib_path" > ~/.Renviron

