#!/bin/bash

# A simple function for lazy git add, commit, and push.

# Fixme: need to insure comments are added correctly.

# Usage:
# lazygit [MESSAGE]
# lazygit "My commit message"

function lazygit(){
	git add .
        git commit -am "${1:-"lazy git commit"}"
        #git commit -a -m "$1"
        git push
}

lazygit $1
