#!/bin/bash

# Launch an ide with vim + tmux.
# Specify a REPL like R or ipython.
# Insure that your .vimrc is set to use iPython for proper execution of indented statements.

# The following should be in your .vimrc:
# let g:slime_target = "tmux"
# let g:slime_default_config = {"socket_name": get(split($TMUX, ","), 0), "target_pane": "bottom"}
# let g:slime_python_ipython = 1

# Usage ide ipython
# Usage ide R

# Create a new Tmux session.
session="ide"
tmux start-server
tmux new-session -d -s $session -n ide 

# Split the pane horizontally and launch vim.
tmux selectp -t 1
tmux splitw -v -p 50
tmux selectp -t 1 
tmux send-keys "vim" C-m

# Enter insert mode and start coding...
tmux send-keys "i" 

# Select the second pane and launch python.
tmux selectp -t 2
tmux send-keys "$1" C-m

# Attach to tmux session.
tmux attach -t ide
