#!/bin/bash

# Create a new Tmux session.
session="ide"
tmux start-server
tmux new-session -d -s $session -n ide

# Split the pane horizontally and launch vim.
tmux selectp -t 1
tmux splitw -v -p 50
tmux selectp -t 1 
tmux send-keys "vim" C-m

# Enter insert mode and start coding...
tmux send-keys "i" 
tmux send-keys "print('hello world')" C-m

# Select the second pane and launch python.
tmux selectp -t 2
tmux send-keys "python" C-m

# Attach to tmux session.
tmux attach -t ide
