#!/bin/bash

## Installation of latex.
sudo apt-get install texlive-xetex

## Installation of the package manager tlmgr. 
sudo apt-get install xzdec
mkdir ~/texmf && cd ~/texmf && sudo tlmgr init-usertree

# Use the older repo inorder to fix error:
# tlmgr: Remote repository is newer than local (2017 < 2019) 
sudo tlmgr option repository ftp://tug.org/historic/systems/texlive/2017/tlnet-final
