#!/bin/bash

## Installing the mps youtube cli.
# From: https://github.com/mps-youtube/mps-youtube

# ~/.local/bin should be in your PATH for --user.
echo "~/.local/bin should be in your PATH"

# With pip:
#pip3 install --user mps-youtube
#pip3 install --user youtube-dl
#pip3 install --user youtube-dl --upgrade

# For mpris2 support, install:
#pip3 install --user dbus-python pygobject

# Alternatively, if using Ubunut:
sudo apt install mps-youtube

echo "mps-youtube is rull using the command:"echo "mpyst"


