#!/bin/bash

# Installing the hub wrapper for git.
# https://askubuntu.com/questions/816540/how-do-you-install-hub-git-wrapper-on-ubuntu-with-autocomplete-and-man-documen

sudo add-apt-repository ppa:cpick/hub
sudo apt-get update
sudo apt-get install hub
