#!/bin/bash

## Installing terminalizer.
#  From: https://github.com/faressoft/terminalizer

# Update
sudo apt-get update

# Install Node.js if it is not already installed.
dpkg -s nodejs &> /dev/null
if [ $? -eq 0 ]; then
    echo "nodejs is already installed!"
else
    echo "Installing nodejs!"
    sudo apt-get install nodejs
fi

# Check that node has installed correctly:
nodejs --version

# Install npm if it is already not installed.
dpkg -s npm &> /dev/null
if [ $? -eq 0 ]; then
    echo "npm is already installed!"
else
    echo "Installing npm!"
    sudo apt-get install npm
fi

# Check the install:
npm --version

# Install terminalizer if it is already not installed.
dpkg -s terminalizer &> /dev/null
if [ $? -eq 0 ]; then
    echo "terminalizer is already installed!"
else
    echo "Installing terminalizer!"
    npm install -g terminalizer
fi

