#!/bin/bash

## Installation of the google calendar cli gcalcli.
# gcalcli: https://github.com/insanum/gcalcli

# Installation:
sudo apt-get install gcalcli

# Configuration:
gcalcli list 

## Usage notes:

# Alias gcalcli as calendar.

# Create a quick event:
# gcalcli --calendar twesleyb10@gmail.com quick 'Dinner with Eric 7 pm tomorrow'

# Check your agenda:
# gcalcli agenda

# Use the convience function add-event to add an event to your calendar!


