#!/bin/bash

# Script for installing Luke Smyth's Mutt-Wizard command line tool.

# Open Github site:
#url=https://github.com/LukeSmithxyz/mutt-wizard
#chrome $url

read -p "Remove old configs? Yes/No: " -n 1 -r 

echo  
if [[ $REPLY =~ ^[Yy]$ ]]
then
	echo "Old configuration files will be removed."
	rm -rf ~/.config/mutt ~/.msmtprc ~/.config/msmtp ~/.offlineimap 
	rm -rf ~/.offlineimaprc ~/.config/offlineimap ~/.mbsyncrc
fi

cd ~/
#git clone https://github.com/LukeSmithxyz/mutt-wizard
#cd mutt-wizard
#sudo make install
