#!/bin/bash

## Installing tpm, a tmux package manager.
# From: https://github.com/tmux-plugins/tpm

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# You will need to edit your tmux configuration file.
echo "Insure you have configured your '~/.tmux.conf'!"
echo "For more instructions, see: https://github.com/tmux-plugins/tpm."

# Configure tmux. 
tmux source ~/.tmux.conf
