#!/bin/bash

## Installing R for Ubuntu 18 on WSL.
# From: https://www.digitalocean.com/community/tutorials/how-to-install-r-on-ubuntu-18-04

# Add the gpg key.
gpg_key="E298A3A825C0D65DFD57CBB651716619E084DAB9"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $gpg_key

# Add the repository. 
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/"

# Update linux apps.
sudo apt-get update -qq -y

# Install R.
sudo apt-get -y install r-base

# Install some other major dependencies.
sudo apt-get install -y build-essential
sudo apt-get install -y libcurl4-gnutls-dev
sudo apt-get install -y libgit2-dev 
sudo apt-get install -y libcurl4-openssl-dev libssl-dev
sudo apt-get install -y zlib1g-dev libssh2-1-dev libpq-dev libxml2-dev 
sudo apt-get install -y libhdf5

# In r as root:
#install.packages("devtools", repos = "https://cran.rstudio.com/")

# Remind the user to install R packages as root user.
echo "Remember to install R packages as root:"
echo "sudo -i R"
