#!/usr/bin/env Rscript
# Install a R package on github.

# Parse the user's input.
require(argparser, quietly = TRUE)
p <- arg_parser("Install a R package on github.")
p <- add_argument(p, "user", help = "package owners git username")
p <- add_argument(p, "package", help = "the package name")
args <- parse_args(p)

# Installation.
cmd <-paste(args$user,args$package,sep="/")
devtools::install_github(cmd)
