#!/bin/bash

# Trouble shooting devtools installation.
# From: https://stackoverflow.com/questions/20923209/problems-installing-the-devtools-package

# Option 1.
#sudo apt install r-cran-devtools

# Option 2.
sudo apt-get update 
sudo apt-get upgrade    

# Insure other dependencies are met.
sudo apt-get -y install libxml2-dev
sudo apt-get -y install libcurl4-gnutls-dev
sudo apt-get -y install libssl-dev

# Update R.
sudo apt-cache showpkg r-base
sudo apt-get install r-base

# Install devtools within R.
echo "Please install devtools within R into your home package directory."
echo "for example: install.packages("devtools","~/local/R_libs")"

# Option 3.
sudo apt-get -y install libcurl4-gnutls-dev
sudo apt-get -y install libssl-dev
