#!/bin/bash

# Install pdflatex-quiet for noiseless compilation:
curl -s https://gitlab.com/jirislav/pdftex-quiet/raw/latest/pdftex-quiet | \
	sudo tee /usr/local/bin/pdftex-quiet >/dev/null \
	&& sudo chmod +x /usr/local/bin/pdftex-quiet \
	&& sudo ln -sf /usr/local/bin/pdftex-quiet /usr/local/bin/pdflatex-quiet

# Usage example
#pdftex-quiet compile-me.tex
# You may also provide additional attributes to `pdflatex`
pdflatex-quiet -output-format=dvi -output-directory=/tmp compile-me.tex

#pdflatex-quiet -v  # or --version
#pdflatex-quiet -h  # or --help

