#!/bin/bash

# Installing ttygif.
# https://github.com/icholy/ttygif

sudo apt-get install imagemagick ttyrec gcc x11-apps make git
cd ~/
git clone https://github.com/icholy/ttygif.git
cd ttygif
make
sudo make install

