#!/bin/bash

# Launch a Jupyter-notebook from WSL.
# A Tmux session will be created to host the jupyter-notebook.
# The notebook will be opened with the Chrome web browser using 
# the `chrome` function.

# Usage:
# launch-jupyter

# fixme: May encounter error if tmux session exists, but server has closed.

# First, check if jupyter-noteook Tmux session exists,
# and launch this notebook.
if tmux ls | grep -q jupyter-notebook; then
	echo "connecting to existing jupyter server..."
	# Check which jupyter server exists.
        jupyter notebook list >> ~/jupyter-server.txt
	sleep 4 
        # Open notebook.
	tmux send-keys -t jupyter-notebook.2 "chrome $(cut -d' ' -f1 ~/jupyter-server.txt | sed -n '2p')" C-m
	rm ~/jupyter-server.txt
	exit
fi

# If server doesn't exist, then launch a new one in Tmux...
echo "starting new jupyter server..."

# Start tmux session.
session="jupyter-notebook"

# Set up tmux
tmux start-server

# Create new window
tmux new-session -d -s $session -n jupyter-notebook

# Split window 1, split horizontally.
tmux selectp -t 1
tmux splitw -h -p 50

# Select pane 1, launch jupyter-notebook.
tmux selectp -t 1
tmux send-keys "jupyter-notebook --no-browser &> jupyter-server.txt" C-m

# Wait for file to be made.
sleep 4

# Select pane 2, open jupyter-notebook.
tmux selectp -t 2
tmux send-keys "chrome $(sed -n '10p' ~/jupyter-server.txt)" C-m

# Remove temporary file.
rm ~/jupyter-server.txt

# Done.
