#!/bin/bash

# Open a file with Windows applications.
# Common extensions: 
# *.txt
# *.md
# *.docx
# *.xlsx
# *.csv
# *.ppt

# Need to add:
# *.eps

#------------------------------------------------------------------------------
# Load bash functions to launch specific Windows applications:
source ~/bin/windows_programs

# Get the input file's extension.
file=$1
filename=$(basename -- "$file")
extension="${filename##*.}"

# If provided, open file with application.
if [ ! -z "$2" ]
then
	application="$2"
	echo "Opening "$filename" with "$application"!"
	$application $file
fi

# Open with appropriate program:
if [ $extension == "txt" ] 
then
	notepad "$1"
elif [ $extension == "docx" ]
then
	word "$1"
elif [ $extension == "doc" ] 
then
	word "$1"
elif [ $extension == "xlsx" ]
then
	excel "$1"
elif [ $extension == "xls" ] 
then
	excel "$1"
elif [ $extension == "csv" ]
then
	excel "$1"
elif [ $extension == "pdf" ]
then
	adobe "$1"
elif [ $extension == "png" ]
then
	paint "$1"
elif [ $extension == "tiff" ]
then
	paint "$1"
elif [ $extension == "pptx" ]
then
	powerpoint "$1"
elif [ $extension == "ppt" ]
then
	powerpoint "$1"
elif [ $extension == "eps" ]
then
	illustrator "$1"
elif [ $extension == "md" ]
then
	open-md "$1"
else
	echo "$extension files are not currently supported!"
fi
