#!/bin/bash

# Preview a markdown file in chrome.
# Requires the Markdown Viewer chrome extension.
# You must also enable file connections and restart chrome. 

# You must execute the open-md command in a new terminal.
# You can't shut down the process.

# Utilize substition to replace the "/home/twesleyb" with windows path:
# ${parameter/pattern/string}

full_path="$PWD/$1"
winpath="${full_path/"/home/twesleyb"/}"
chrome "file:///d:$winpath"

