#!/bin/bash

# Remove temporary files.

read -p "Temporary .swp, .swl, .swm, and .swn files will be deleted. Proceed? Yes/No " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	rm -rf ls *.swp *.swl *.swm *.swn
	echo "Files removed."
fi
