#!/bin/bash

# Simpler timer:
#while true; do echo -ne "`date`\r"; done

function stopwatch(){
	date1=`date +%s`;
	while true; do
		echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
		sleep 0.1
	done
}

source stopwatch
stopwatch 
