#!/bin/bash

# Updating R.
# From: https://github.com/duckmayr/install-update-r-on-linux

# Add the authorization key.
key="E298A3A825C0D65DFD57CBB651716619E084DAB9"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $key

# Download the most recent verion of R.
cran_mirror="http://cran.wustl.edu/bin/linux/ubuntu bionic-cran35/"
sudo echo "deb $cran_mirror" | sudo tee -a /etc/apt/sources.list
sudo apt update

# Upgrade R.
sudo apt upgrade

# Insure that R packages are up-to-date.
#~/bin/update-r-packages

echo "see the end of this script for alternative instructions!"

exit

## Alternative instructions:
#  From https://www.r-bloggers.com/updating-r-on-ubuntu/
# Add R source for your appropriate ubuntu distro:
# Too see which ubuntu version you have:
#lsb_release -a # bionic
#echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" >> /etc/apt/sources.list

