#!/bin/bash

# One liners to launch windows programs.
notepad () { "/mnt/c/WINDOWS/system32/notepad.exe" "$1"; }
excel () { "/mnt/c/Program Files/Microsoft Office/root/Office16/EXCEL.EXE" "$1"; }
word () { "/mnt/c/Program Files/Microsoft Office/root/Office16/WINWORD.EXE" "$1"; } 
adobe () { "/mnt/c/Program Files (x86)/Adobe/Acrobat Reader DC/Reader/AcroRd32.exe" "$1"; }
powerpoint () { "/mnt/c/Program Files/Microsoft Office/root/Office16/POWERPNT.EXE" "$1"; }
paint () { "/mnt/c/WINDOWS/system32/mspaint.exe" "$1"; }
illustrator () { "/mnt/c/Program Files/Adobe/Adobe Illustrator CC 2019/Support Files/Contents/Windows/illustrator.exe" "$1"; }
